name: CI

on:
  push:
    branches:
      - Main
  pull_request:

jobs:
  use-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

        with:
          node-version: "15.8.0"
      - name: Install repo dependencies
        run: npm install
      - name: Build and deploy
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
