name: CI

on:
  push:
    branches:
      - Main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Dependencies
        run: npm install
      - name: setup git config
        run: |
          git config --global user.email "jonakirke94@gmail.com" 
          git config --global user.name "Jonathan"
      - name: Build and deploy
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
